# Generated by Django 5.0.2 on 2024-02-26 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ccad4438-aa41-4cbf-8ecf-79ea52fc4808'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
